export const FETCH_RECENT = "FETCH_RECENT";
export const CREATE_QUESTION = "CREATE";
export const LIKE_QUESTION = "LIKE";
export const DISLIKE_QUESTION = "DISLIKE";
export const SEARCH_QUESTION = "SEARCH";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";

export const FETCH_THREAD = "FETCH_THREAD";
export const LIKE_THREAD_QUESTION = "LIKE_THREAD_QUESTION";
export const DISLIKE_THREAD_QUESTION = "DISLIKE_THREAD_QUESTION";

export const POST_ANSWER = "POST_ANSWER";
export const UPDATE_ANSWER = "UPDATE_ANSWER";

export const LIKE_THREAD_ANSWER = "LIKE_THREAD_ANSWER";
export const DISLIKE_THREAD_ANSWER = "DISLIKE_THREAD_ANSWER";
export const DELETE_ANSWER = "DELETE_ANSWER";

export const SEARCH_AUTOCOMPLETE = "SEARCH_AUTOCOMPLETE";

export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";

export const FETCH_TOP_USER = "FETCH_TOP_USER";
export const FETCH_TOP_CATEGORY = "FETCH_TOP_CATEGORY";
